services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # MinIO API port
      - "9001:9001"  # MinIO Console port
    environment:
      MINIO_ROOT_USER: minioadmin  # Default root user
      MINIO_ROOT_PASSWORD: minioadmin  # Default root password
    volumes:
      - minio_data:/data  # Persistent storage for MinIO data
    command: server /data --console-address ":9001"
    

volumes:
  minio_data:  # Named volume for MinIO data persistence

